postcode:
    processor:
        target_type_name: UK Parliament constituency
    client:
        base_url: http://mapit.mysociety.org/postcode
candidate:
    processor:
    client:
        apikey: API-KEY-GOES-HERE
        base_url: http://www.theyworkforyou.com/api/getMP?output=js
voting_records:
    client:
        base_url: http://www.publicwhip.org.uk/division.php
    relevant_issues:
        -
            name: Reduce age of consent for homosexual acts to 16
            votes:
                -
                    name: Second Reading
                    date: "1998-06-22"
                    number: 311
        -
            name: Marriage (Same Sex Couples)
            votes:
                -
                    name: Third Reading
                    date: "2013-02-05"
                    number: 151

