postcode:
    processor:
        target_type_name: UK Parliament constituency
    client:
        base_url: http://mapit.mysociety.org/postcode
candidate:
    processor:
    client:
        base_url: http://www.theyworkforyou.com/api/getMP?output=js
voting_records:
    client:
        base_url: http://www.publicwhip.org.uk/division.php
    relevant_issues:
        -
            name: Reduce age of consent for homosexual acts to 16
            votes:
                -
                    name: Second Reading
                    date: "1998-06-22"
                    number: 311
        -
            name: Repeal of section 28
            votes:
                -
                    name: Third Reading
                    date: "2003-03-10"
                    number: 111
        -
            name: Introduction of Civil Partnerships
            votes:
                -
                    name: Second Reading
                    date: "2004-10-12"
                    number: 256
                -
                    name: Third Reading
                    date: "2004-11-09"
                    number: 315
        -
            name: Equality Act (Sexual Orientation) Regulations
            votes:
                -
                    name: Vote
                    date: "2007-03-19"
                    number: 79
        -
            name: IVF treatment for lesbian couples
            votes:
                -
                    name: Vote
                    date: "2007-03-19"
                    number: 79
        -
            name: Marriage (Same Sex Couples)
            votes:
                -
                    name: Second Reading
                    date: "2013-02-05"
                    number: 151
                -
                    name: Third Reading
                    date: "2013-05-21"
                    number: 11
